### PR TITLE
feat: path level access control

### PR DESCRIPTION
**Pull request by sigoden**
Duf supports path level access control through option `--auth`/`-a`.

Grammar rule:

```
<path>@<readwrite>[@<readonly>]
```

- `<path>`: Path to protected
- `<readwrite>`: Account with readwrite permission
- `<readonly>`: Account with readonly permission

> If `<readonly>` is `*`, means `<path>` is public, everyone can acess/download it.

BREAKING CHANGE: `--auth` is changed, `--no-auth-access` is removed

### CODE REVIEW

**Comment by molezz** [comment]
```
./dufs -a /temp@* -a /@admin:admin
error: Invalid auth `/deb11@*
```
我想让开放deb11目录,但是其他的需要授权,根据readme运行, 但似乎不支持*?

**Comment by sigoden** [comment]
`dufs -a /temp@admin:admin@* -a /@admin:admin`

**Comment by molezz** [comment]
ok 有点明白了

**Comment by molezz** [comment]
> `dufs -a /temp@admin:admin@* -a /@admin:admin`
多谢
还有个想请教的,readme说 最后A只影响跟着那个-a,但是我
`/dufs -a /temp@admin:admin@* -a /@admin:admin -A` 
结果temp不登陆也有删除和上传权限 . <readonly>这个flag怎么加呢?

**Pull request merged**
