### PR TITLE
added "Empty folder" text to the page

### PR DESCRIPTION
**Pull request by jkoop**
image

### CODE REVIEW

**Comment by sigoden** [comment]
Three will be two situration for empty listing:

1. The direcotry do not exist
2. The directory exist but it is empty

I don't think it's necessary to add `Empty folder`

**Comment by jkoop** [comment]
A bare page looks like a program crash to lots of people.

For a directory that doesn't exist, I get a 404:

image

**Comment by sigoden** [comment]
Check `http://localhost:5000/dfghj/`. Suffix `/` is requried to distinct file and folder.

**Comment by sigoden** [comment]
You can upload files and directorys to directory does not exist yet。No need to manually create folder.

**Comment by jkoop** [comment]
image

**Comment by sigoden** [comment]
It works only when your allow upload

**Comment by jkoop** [comment]
Fixed

image
image
image

**Pull request merged**
